# Generated by Django 3.2.12 on 2023-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='gpt_rating',
            field=models.IntegerField(choices=[(0, 'Safe'), (1, 'Moderate'), (2, 'High Risk')], default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='show_to_user',
            field=models.BooleanField(default=True),
        ),
    ]
